# Generated by Django 3.2.3 on 2021-05-20 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TollReceipt',
            fields=[
                ('receipt_id', models.AutoField(default=10000, primary_key=True, serialize=False)),
                ('vehicle_number', models.CharField(max_length=10)),
                ('journey_type', models.CharField(choices=[('OW', 'Single Journey'), ('TW', 'Return Journey')], default='OW', max_length=2)),
                ('vehicle_type', models.CharField(choices=[('CR', 'Car/Jeep'), ('BS', 'Buses'), ('TK', 'Trucks')], default='CR', max_length=2)),
                ('journey_date_time', models.DateTimeField(auto_now_add=True)),
                ('journey_status', models.CharField(max_length=10)),
                ('journey_towards', models.CharField(max_length=255)),
            ],
        ),
    ]
