# Generated by Django 3.2.3 on 2021-05-20 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipt', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tollreceipt',
            name='price',
            field=models.IntegerField(choices=[(100, 100), (200, 200)], default=100),
        ),
    ]
