# Generated by Django 3.2.3 on 2021-05-21 10:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipt', '0004_alter_tollreceipt_journey_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tollreceipt',
            name='journey_date_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 21, 15, 30, 43, 405085)),
        ),
        migrations.AlterField(
            model_name='tollreceipt',
            name='receipt_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
