# Generated by Django 3.2.3 on 2021-05-21 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipt', '0006_alter_tollreceipt_journey_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tollreceipt',
            name='journey_date_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
